import type { Metadata } from "next";
import { Noto_Sans } from "next/font/google";
import "./globals.css";
import { anabelle } from "./fonts";
import 'swiper/css';
import 'swiper/css/navigation';
import ReactLenis, { useLenis } from "lenis/react";
import LenisProvider from "@/providers/lenis";
import Footer from "@/components/common/footer";

const geistSans = Noto_Sans({
  variable: "--font-noto-sans",
  subsets: ["latin"],
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {


  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${anabelle.variable} antialiased`}
      >
        <LenisProvider>
          {children}
          <Footer />
        </LenisProvider>
      </body>
    </html >
  );
}
